version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=izzanzahrial
      - POSTGRES_PASSWORD=izzanzahrial
      - POSTGRES_DB=pgdocker
  redis:
    image: redis:6.2-alpine
    # for running with the same redis config
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    # move redis config from local to container
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=izzanzahrial
      - discovery.seed_host=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      # minimum and maximum memory usage
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # lock memory usage for elasticsearch, read this part again
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=izzanzahrial
      - discovery.seed_host=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      # minimum and maximum memory usage
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # lock memory usage for elasticsearch, read this part again
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    ports:
      - 9201:9201
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.3
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=izzanzahrial
      - discovery.seed_host=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      # minimum and maximum memory usage
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # lock memory usage for elasticsearch, read this part again
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    ports:
      - 9202:9202
    networks:
      - elastic
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - redis
    entrypoint: [ "postgres:5432", "/app/start.sh"]
    command: [ "/app/main" ]

volumes:
  data01:
    driver: local
  data02:
    driver: local
  data03:
    driver: local

networks:
  elastic:
    driver: bridge