version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=izzanzahrial
      - POSTGRES_PASSWORD=izzanzahrial
      - POSTGRES_DB=pgdocker
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    entrypoint: [ "postgres:5432", "/app/start.sh"]
    command: [ "/app/main" ]