version: "3.9"
services:
  postgres:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=izzanzahrial
      - POSTGRES_PASSWORD=izzanzahrial
      - POSTGRES_DB=pgdocker
  redis:
    image: redis:6.2-alpine
    # untuk menjalankan sesuai redis config
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    # memindahkan redis config local ke dalam container
    volumes:
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    entrypoint: [ "postgres:5432", "/app/start.sh"]
    command: [ "/app/main" ]